# Generated by Django 5.2.4 on 2025-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_discount_tax_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.FloatField(default=0, help_text='Discount percentage (e.g. 20 for 20%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.FloatField(default=0, help_text='Tax percentage (e.g. 15 for 15%)'),
            preserve_default=False,
        ),
    ]
